Updates to support DDR5
open-power/common-mrw-xml pull request #1006
Opened 2023-03-29 20:39 UTC by ruby452

2023-03-29 20:53 UTC, dcrowell77 commented on parts/lcard-dimm-ddimm.xml
> +    <child_id>ddr4</child_id>
Having ddr4+ddr5 is good for now but I will probably be making a suggestion that we change to a generic "ddr" name since they aren't really handled exclusively.  Since Odyssey needs 2 ddrs, we should really have 1xddr4 and 2xddr5, but I think having 2xddr is simpler.  This is all a work-in-progress though so stay tuned...

2023-03-29 20:58 UTC, dcrowell77 reviewed
This is a fine start, but there will be more changes.  I suggest that you wait until we get a working prototype for one platform.  Otherwise we risk producing unuseable xml files if other systems pull this in.

2023-03-29 21:05 UTC, IlyaSmirnov91 approved these changes

2023-06-05 16:37 UTC, dcrowell77 commented on parts/lcard-dimm-ddimm.xml
> +	<type>unit-ddr4-jedec</type>
Switch to using the generic "unit-ddr" type instead, otherwise it is a bit nonsensical.  The current parsing code supports all the names the same way but it makes more sense to not have them be ddr-specific.

2023-06-05 16:38 UTC, dcrowell77 requested changes
Update naming scheme

2023-06-07 14:33 UTC, ruby452 commented
@dcrowell77 I have made the changes you requested. Can you do another review please?

2023-06-07 17:50 UTC, dcrowell77 approved these changes

2023-06-07 17:51 UTC, merged